name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: 테스트 및 빌드하기
        run: sudo ./gradlew clean build

      - name: SSH로 EC2에 접속하기a
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/gitCicdTestServer/current
            mkdir /home/ubuntu/gitCicdTestServer/current
            mv /home/ubuntu/gitCicdTestServer/tobe/project.jar /home/ubuntu/gitCicdTestServer/current/project.jar
            cd /home/ubuntu/gitCicdTestServer/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar > ./output.log 2>&1 & 
            rm -rf /home/ubuntu/gitCicdTestServer/tobe