name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치 test
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Java 버전 확인
        run: java -version

      - name: Gradle에 JAVA_HOME 설정
        run: |
          echo $JAVA_HOME
          export JAVA_HOME=$(which java)
          ./gradlew clean build

      - name: 테스트 및 빌드하기
        run: | 
          echo $JAVA_HOME
          chmod +x gradlew
          ./gradlew clean build